주피터 SQL 엔진 설정

In [ ]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [ ]:
# ID와 PW를 자신의 환경에 맞게 수정
%sql postgresql://guest:Guest1234@ssde.cnqux5xggmn5.us-east-2.redshift.amazonaws.com:5439/dev

'Connected: guest@dev'

데이터 형태 확인

In [ ]:
%%sql

SELECT *
FROM raw_data.user_session_channel
LIMIT 2;

 * postgresql://guest:***@ssde.cnqux5xggmn5.us-east-2.redshift.amazonaws.com:5439/dev
2 rows affected.

[(1651, '0004289ee1c7b8b08c77e19878106ae3', 'Organic'),
 (1197, '00053f5e11d1fe4e49a221165b39abc9', 'Facebook')]

In [ ]:
%%sql

SELECT *
FROM raw_data.session_timestamp st
LIMIT 2;

 * postgresql://guest:***@ssde.cnqux5xggmn5.us-east-2.redshift.amazonaws.com:5439/dev
2 rows affected.

[('00029153d12ae1c9abe59c17ff2e0895', datetime.datetime(2019, 10, 18, 14, 14, 5, 100000)),
 ('0004289ee1c7b8b08c77e19878106ae3', datetime.datetime(2019, 11, 16, 21, 20, 14, 447000))]

월별 액티브한 사용자들 수 카운트.

In [ ]:
%%sql

select to_char(DATE(st.ts), 'YYYY-MM') as yearmonth, count(distinct usc.userid)
FROM raw_data.session_timestamp st
JOIN raw_data.user_session_channel usc
ON st.sessionid = usc.sessionid
GROUP BY yearmonth
ORDER BY yearmonth

 * postgresql://guest:***@ssde.cnqux5xggmn5.us-east-2.redshift.amazonaws.com:5439/dev
7 rows affected.

[('2019-05', 281),
 ('2019-06', 459),
 ('2019-07', 623),
 ('2019-08', 662),
 ('2019-09', 639),
 ('2019-10', 763),
 ('2019-11', 721)]